name: Applications

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        buildtype: ["Debug", "Release"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git name
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git --version

      - name: Configure Windows
        if: matrix.os == 'windows-latest'
        run: cmake ${{github.workspace}} -Ax64 -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.buildtype}} -DPACKAGE_OUTPUT_FILE_PREFIX=${{github.workspace}}/dist -DENABLE_SWIG=OFF -DENABLE_PORTABLE=ON -DDISABLE_PACKAGE_SUBDIR=ON

      - name: Configure OSX
        if: matrix.os == 'macOS-latest'
        run: cmake ${{github.workspace}} -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.buildtype}} -DPACKAGE_OUTPUT_FILE_PREFIX=${{github.workspace}}/dist -DENABLE_SWIG=OFF -DENABLE_PORTABLE=ON -DDISABLE_PACKAGE_SUBDIR=ON

      - name: Build OSX and Windows
        if: matrix.os != 'ubuntu-latest'
        run: cmake --build build --config ${{matrix.buildtype}}

      - name: Test OSX and Windows
        if: matrix.os != 'ubuntu-latest'
        run: cmake --build build --config ${{matrix.buildtype}} --target check

      - name: Package OSX and Windows
        if: matrix.os != 'ubuntu-latest'
        run: cmake --build build --config ${{matrix.buildtype}} --target bundle

      - name: Linux Build, Test and Package in Docker
        if: matrix.os == 'ubuntu-latest'
        run: docker run --rm -v ${{github.workspace}}/:/io ezralanglois/interop bash -c "cmake /io -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.buildtype}} -DPACKAGE_OUTPUT_FILE_PREFIX=/io/dist -DENABLE_SWIG=OFF -DENABLE_PORTABLE=ON -DDISABLE_PACKAGE_SUBDIR=ON && cmake --build build && cmake --build build --target check && cmake --build build --target bundle"

      - name: Test Artifacts
        run: ls dist/*

      - uses: actions/upload-artifact@v4
        if: matrix.buildtype == 'Release'
        with:
          name: artifact_${{matrix.os}}
          path: dist/*.*

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Publish Artifacts to Github Releases
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}