name: Applications

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        buildtype: ["Debug", "Release"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git name
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git --version

      - name: Configure Windows
        if: matrix.os == 'windows-latest'
        run: cmake ${{github.workspace}} -Ax64 -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.buildtype}} -DPACKAGE_OUTPUT_FILE_PREFIX=${{github.workspace}}/dist -DENABLE_SWIG=OFF

      - name: Configure OSX
        if: matrix.os == 'macOS-latest'
        run: cmake ${{github.workspace}} -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.buildtype}} -DPACKAGE_OUTPUT_FILE_PREFIX=${{github.workspace}}/dist -DENABLE_SWIG=OFF

      - name: Build OSX and Windows
        if: matrix.os != 'ubuntu-latest'
        run: cmake --build build --config ${{matrix.buildtype}}

      - name: Test OSX and Windows
        if: matrix.os != 'ubuntu-latest'
        run: cmake --build build --config ${{matrix.buildtype}} --target check

      - name: Package OSX and Windows
        if: matrix.os != 'ubuntu-latest'
        run: cmake --build build --config ${{matrix.buildtype}} --target bundle

      - name: Linux Build, Test and Package in Docker
        if: matrix.os == 'ubuntu-latest'
        run: docker run --rm -v ${{github.workspace}}/:/io ezralanglois/interop bash -c "cmake /io -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.buildtype}} -DPACKAGE_OUTPUT_FILE_PREFIX=/io/dist -DENABLE_SWIG=OFF && cmake --build build && cmake --build build --target check && cmake --build build --target bundle"

      - uses: actions/upload-artifact@v3
        if: matrix.buildtype == 'Release'
        with:
          path: dist/*.*
